export const ReportCategory = {
  SECURITY: 'SECURITY',
  CROWD: 'CROWD',
  FACILITY: 'FACILITY',
  OTHER: 'OTHER'
};

export const ReportStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED'
};

export const SpotType = {
  ENTRY_GATE: 'ENTRY_GATE',
  EXIT_GATE: 'EXIT_GATE',
  CHECKPOINT: 'CHECKPOINT',
  SHELTER: 'SHELTER',
  INFO_CENTER: 'INFO_CENTER',
  STAGE: 'STAGE',
  REST_AREA: 'REST_AREA',
  VIEW_POINT: 'VIEW_POINT',
  DANGER_ZONE: 'DANGER_ZONE',
  MEETING_POINT: 'MEETING_POINT',
  HOSPITAL: 'HOSPITAL',
  OTHER: 'OTHER'
};
